### ISSUE TITLE
Re

### ISSUE THREAD

**Issue by akikic** [bitfocus/companion-module-requests#1334] opened 2023-12-03 19:42 UTC
Hi,

First, thank you for your wonderful piece of software. It would be awesome if "Axoa 3D free audio app for performing arts" would be fully supported !

This software support OSC connection.

Thanks for all

**Comment by bryce-seifert** [comment] 2023-12-15 02:30
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1335

**Closed as not planned by bryce-seifert** 2023-12-15 02:30 UTC
