### ISSUE TITLE
Thor RF11iQ PDU

### ISSUE THREAD

**Issue by MikeTechnical** [bitfocus/companion-module-requests#1229] opened 2023-07-29 10:11 UTC
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Thor RF11iQ PDU

What you would like to be able to make it do from Companion:
Switch outlets with feedback

Direct links or attachments to the ethernet control protocol or API:
https://www.thortechnologies.com.au/product/thor-smartbrain-rf11iq/

**Comment by bryce-seifert** [comment] 2023-08-04 21:47
On the product page linked, it says  `Control System integration with supplied API (on request).`

Would you be able to get in touch with them, and get the API documentation?

**Comment by bryce-seifert** [comment] 2023-08-04 21:49
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/660

**Closed as not planned by bryce-seifert** 2023-08-04 21:49 UTC
Labels: Missing documentation, Hardware

**Comment by MikeTechnical** [comment] 2023-08-07 04:23
Here is the API Document for the Thor RF11iQ
[RF11iQP API Thor Technologies Pty Ltd.docx](https://github.com/bitfocus/companion-module-requests/files/12272022/RF11iQP.API.Thor.Technologies.Pty.Ltd.docx)
