### ISSUE TITLE
Module Request: Sharp TV Control

### ISSUE THREAD

**Issue by blitzkrieggold** [bitfocus/companion-module-requests#44] opened 2019-02-14 00:17 UTC
**Describe the feature**
Control of a Sharp TV. Source selection, channel selection, volume control.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
This is a clip from the manual of a Sharp pn-le701 display containing the commands needed to control the tv.
[SharpTVcommands.pdf](https://github.com/bitfocus/companion/files/2862767/SharpTVcommands.pdf)

**Usecases**
We use these as displays in an auditorium setting as well as in meeting rooms.

**Comment by McHauge** [comment] 2019-10-15 08:37
Ups kinda overlooked this one, but it's kinda a duplicate of #96 and the module is now in testing and should work with all sharp monitors/tv's, I'll add the channel option to the module

**Comment by josephdadams** [comment] 2019-11-02 12:26
@McHauge can we close this one?

**Comment by McHauge** [comment] 2019-11-02 12:36
@josephdadams sure but was kinda waiting for some test result before doing it myself

**Comment by McHauge** [comment] 2019-11-19 12:04
Gonna close this one, it' included in the V2.0 core and if errors come up, then we will take it from there.

**Closed by McHauge** 2019-11-19 12:04 UTC
Labels: Hardware, Needs testers
