### ISSUE TITLE
Worship Presenter from WorshipTools

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-requests#1397] opened 2024-02-06 16:34 UTC
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: **Worship Presenter from WorshipTools**

What you would like to be able to make it do from Companion:
- next/previous slide
- next/previous plan item
- name of current plan item
- name of next plan item
- blank screen

Direct links or attachments to the ethernet control protocol or API: none known.

This is a dupe of #1385 but with the requested details.

**Comment by bryce-seifert** [comment] 2024-02-09 23:25
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1385.

Feel free to add your requests as a comment on that issue

**Closed as not planned by bryce-seifert** 2024-02-09 23:25 UTC
Labels: NOT YET PROCESSED

**Comment by jgclark** [comment] 2024-02-09 23:27
Done. This can be closed, and #1385 updated.
