### ISSUE TITLE
Playstation Controller or generic joystick/gamepad/gamecontroller

### ISSUE THREAD

**Issue by apochroma** [bitfocus/companion-module-requests#762] opened 2022-03-31 16:01 UTC
I was pleased to see that there is now a module for the Canon PTZ cameras. Now it would be very interesting if you could connect a Playstation controller to control the camera remotely.
I can connect a PS4 controller to a Rapsberry Pi 4. I have installed this software:
https://pypi.org/project/pyPS4Controller/

I can fire single button presses using UDP. But I have no idea how to do this if I want to simulate a continuous button press.

Is there any interest in implementing a game controller?
I could imagine that many PTZ users would be happy about this feature.

**Comment by josephdadams** [comment] 2022-04-01 13:19
duplicate of https://github.com/bitfocus/companion/issues/1139

Most PTZs have a "start moving left" and a "stop moving left" for example, so if you are using that program, you would just simulate pressing a button that starts moving it in the direction you want, and then when you release that direction, sends the stop command for that axis.

**Closed** 2022-04-01 13:20 UTC
