### ISSUE TITLE
ATLONA AT-JUNO-451 TCP request

### ISSUE THREAD

**Issue by Soloux** [bitfocus/companion-module-requests#1168] opened 2023-05-28 18:29 UTC
HI all, I have recently been able to telnet into my HDMI switcher and use the API commands to control it. But when I try to log in through TCP in companion, I am able to get it to connect but not receive the commands. my theory is that the generic TCP module isn't capable of sending the correct carriage commands. Can someone please help me? I will include the API.

https://atlona.com/product/at-juno-451/

[AT-JUNO-451_HDBT_API.pdf](https://github.com/bitfocus/companion-module-requests/files/11585411/AT-JUNO-451_HDBT_API.pdf)

**Comment by Soloux** [comment] 2023-05-28 18:36
![image](https://github.com/bitfocus/companion-module-requests/assets/27856685/f7b59302-6ef1-45ab-9981-560e8a075238)


this solved my problem actually. I ended up trying a different appendation. Please try to make this a connection in the future.

**Comment by josephdadams** [comment] 2023-05-28 18:42
duplicate of #156

**Closed as completed by josephdadams** 2023-05-28 18:42 UTC
