### ISSUE TITLE
GEFEN HDMI MATRIX EXT-HD-SL-444

### ISSUE THREAD

**Issue by fwccogmedia** [bitfocus/companion-module-requests#718] opened 2022-02-05 20:51 UTC
I'd like to connect to my HDMI matrix and have buttons that select the 10 presets. I'd also like feedback color on the button to show which preset is active. The matrix is on the network and the manual describes the connections but I have not been able to figure it out. Is it possible this hardware can be added? Thank you. https://www.manualslib.com/manual/1021633/Gefen-Ext-Hd-Sl-444.html

**Comment by josephdadams** [comment] 2022-02-08 21:49
Duplicate of #426

**Closed by josephdadams** 2022-02-08 21:49 UTC
Labels: Hardware, Easy
