### ISSUE TITLE
Aja FS4 Api

### ISSUE THREAD

**Issue by cyblex1** [bitfocus/companion-module-requests#606] opened 2021-10-10 19:30 UTC
I would like to be able to control the Video and Audio Channel Mapping of an Aja FS4 UNit.

It has an Rest Api, it should be not a big problem to implement that.

Manual is available from https://www.aja.com/assets/support/files/8122/en/AJA_FS4_Manual_v2.0r2.pdf

**Comment by josephdadams** [comment] 2021-10-10 23:22
Duplicate of #8

**Closed by josephdadams** 2021-10-10 23:22 UTC
