### ISSUE TITLE
Barco RLM Projectors

### ISSUE THREAD

**Issue by G-Hansen** [bitfocus/companion-module-requests#234] opened 2020-06-12 20:37 UTC
I have a Barco RLM w14 that i would love to control with companion.

**Comment by josephdadams** [comment] 2020-06-12 23:25
Duplicate of #2

**Closed by josephdadams** 2020-06-12 23:25 UTC

**Comment by myrservice** [comment] 2025-07-30 19:11
i have a w8 that i am using http call requests for but would love direct control through module
