### ISSUE TITLE
Livestream Studio Support would be great

### ISSUE THREAD

**Issue by JohnNorris92** [bitfocus/companion-module-requests#507] opened 2021-05-25 05:23 UTC
Livestream Studio Support would be great, Especially as there is currently no hotkeys to control audio or Aux inputs/outputs or toggle layers inside graphics layers.

Thanks

**Comment by josephdadams** [comment] 2021-05-31 22:31
Duplicate of #119

**Closed by josephdadams** 2021-05-31 22:31 UTC
