### ISSUE TITLE
Samsung Control Module?

### ISSUE THREAD

**Issue by jlklein** [bitfocus/companion-module-requests#274] opened 2020-09-01 04:24 UTC
Hi, I'm just getting into Stream Deck and Companion for volunteer tech team member control of various things at church, such as video routing equipment, projectors and display control.  We have a number of Samsung TU7000 TV models that we'd like to be able to at least remotely power on and off but there doesn't seem to be a module available (only for Sharp and Roku TV). We're feeding them with a Blackmagic SDI Smart VideoHub (matrix switcher), but have to walk around with a remote and power them on and off at the start and end of Sunday Services each week and sometimes they get forgotten, so remote control would help that a lot. 

Thansk,
Jeff

**Comment by josephdadams** [comment] 2020-09-01 10:40
Missing documentation and possible duplicate of #102

**Closed by josephdadams** 2020-09-01 10:40 UTC
