### ISSUE TITLE
Connection to ADJ mydmx

### ISSUE THREAD

**Issue by valfilippo** [bitfocus/companion-module-requests#1017] opened 2023-01-09 13:37 UTC
There is a plug in to connect mydmx 3.0 aDJ?

**Comment by QuinnMatthews** [comment] 2023-02-06 20:44
Duplicate of #1038 (This one is technically older, but the other has more detail)

**Comment by josephdadams** [comment] 2023-02-23 16:04
closed because duplicate

**Closed as completed by josephdadams** 2023-02-23 16:04 UTC
Labels: NOT YET PROCESSED
