### ISSUE TITLE
VISCA for AIDA PTZ-X20-IP

### ISSUE THREAD

**Issue by dangoldeasterbunny** [bitfocus/companion-module-requests#832] opened 2022-06-12 21:49 UTC
hey there. im operating a 4 camera live music stream and someone smart just introduced me to Companion. There are so many things that I've just faked my way through using streamdeck and obs, but  now I can do them the right way with companion (ie. slow digital zoom in/out for a dramatic shot - it was ok, but digital zoom sucks when I have 20x optical I could be using) So thanks for that!

Anyhow there is no preset connection for my cameras and the text link said to make requests here. So here I am. Making a request.

What's next?
thanks.

mx
Live from Norfolk Street
https://www.youtube.com/channel/UCBdl3Ww-zIfOR7iMQbZmhLQ

**Comment by krocheck** [comment] 2022-06-12 23:20
Pretty sure I've had success with ADIA cameras, including presets, using the Sony VISCA module.

**Comment by dangoldeasterbunny** [comment] 2022-06-12 23:44
right on.

im actually using the PTZOptics module and it's pretty good, but there are some commands that don't work properly and a few that don't work at all. Unfortunately they are the ones that I'm needing the most (zoom speed, save p/t preset, recall p/t preset, and a few others I cant remember atm.)

**Comment by josephdadams** [comment] 2022-07-09 13:40
Duplicate of #281

**Closed by josephdadams** 2022-07-09 13:40 UTC

**Comment by dangoldeasterbunny** [comment] 2022-07-09 15:53
so i guess that’s a ‘no’ then?

**Comment by josephdadams** [comment] 2022-07-09 16:06
No, it’s just a duplicate request and I don’t like having multiple open issues for the same thing

**Comment by dangoldeasterbunny** [comment] 2022-07-09 16:57
ok. since the other ticket has been open since 2020, i should i be looking for another solution?

**Comment by josephdadams** [comment] 2022-07-09 17:02
There’s over 400 open module requests. At this point, the only new modules getting made are by people who need it so badly they either code it themselves or they hire it out. If you’re interested in the latter, my email is listed in my github profile.
