### ISSUE TITLE
Support for biamp TerisaForte DSP

### ISSUE THREAD

**Issue by doubledeej** [bitfocus/companion-module-requests#1311] opened 2023-11-14 16:22 UTC
biamp makes a rackmount digital signal processor called the TerisaForte. They have it in versions which support analog audio, AVB, Dante, VoIP, and other audio signal types. 

The basic idea of the product is that you can create your own signal flows and add whatever processing you want. It includes mixers, equalizers, compressors/expanders. It also has its own logic flows so you can, based on your own set of rules, alter the way that signals are routed, or turn modules on and off. And each of these modules has the ability to be controlled remotely via a TCP connection.  It also has the ability to send TCP command strings to external devices as well based on things happening internally.

Control of the device by Companion seems like a perfect fit. And I believe other devices in their product line use the same, or at least a similar, protocol for control.

https://support.biamp.com/Tesira/Control/Tesira_network_ports_and_protocols

**Comment by bryce-seifert** [comment] 2023-11-21 00:39
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/406

**Closed as not planned by bryce-seifert** 2023-11-21 00:39 UTC
