### ISSUE TITLE
Z-Cam E2 Series

### ISSUE THREAD

**Issue by wingertandrew** [bitfocus/companion-module-requests#273] opened 2020-08-29 17:50 UTC
Hello All! 

First time here, looking to see if there’s a possibly of getting record control and feedback from the camera. It uses IP control. 

http://www.z-cam.com/open-api-sdk/

Thanks! Let me know if there’s any questions I can answer.

**Comment by josephdadams** [comment] 2020-08-29 23:00
Duplicate of #195

**Closed by josephdadams** 2020-08-29 23:00 UTC
Labels: Hardware
