### ISSUE TITLE
Allen & Heath Qu series audio desks

### ISSUE THREAD

**Issue by Columbo818** [bitfocus/companion-module-requests#343] opened 2020-12-30 15:52 UTC
dLive and iLive are supported. Is it possible to add the Qu series?
Existing module: https://github.com/bitfocus/companion-module-allenheath-dlive
Qu Series MIDI protocol: https://www.allen-heath.com/media/Qu_MIDI_Protocol_V1.9.pdf

I've not got access to a Qu unit to check if the existing module will work.

**Comment by josephdadams** [comment] 2020-12-30 22:16
Duplicate of #91

**Closed by josephdadams** 2020-12-30 22:16 UTC
