### ISSUE TITLE
LG TV control

### ISSUE THREAD

**Issue by streamav** [bitfocus/companion-module-requests#1596] opened 2024-08-29 05:57 UTC
Proffesional TV's like the LG UH5 series 
we control now with tcp

power on/off
switching sources 
would be perfect

**Comment by joeltcaron** [comment] 2024-10-11 06:22
ka 00 00 // power off
ka 00 01 // power on
xb 00 90 // hdmi 1
xb 00 91 // hdmi 2
xb 00 92 // hdmi 3
xb 00 93 // hdmi 4
kc 00 01 // screen mute on

Port 9761
TCP Command
Requires Wake on lan via Mac address to power on

**Comment by streamav** [comment] 2024-10-11 06:33
super thankyou!
________________________________
Van: Joel Caron ***@***.***>
Verzonden: vrijdag 11 oktober 2024 08:22
Aan: bitfocus/companion-module-requests ***@***.***>
CC: Pieter Boer van Stream AV ***@***.***>; Author ***@***.***>
Onderwerp: Re: [bitfocus/companion-module-requests] LG TV control (Issue #1596)


ka 00 00 // power off
ka 00 01 // power on
xb 00 90 // hdmi 1
xb 00 91 // hdmi 2
xb 00 92 // hdmi 3
xb 00 93 // hdmi 4
kc 00 01 // screen mute on

Port 9761
TCP Command
Requires Wake on lan via Mac address to power on

**Comment by peternewman** [comment] 2024-10-14 17:13
I think this is a duplicate of https://github.com/bitfocus/companion-module-requests/issues/224 .

But seem some positive noises in my comment here https://github.com/bitfocus/companion-module-requests/issues/224#issuecomment-2411819022

**Comment by josephdadams** [comment] 2024-10-16 15:51
duplicate of #224

**Closed as completed by josephdadams** 2024-10-16 15:51 UTC
Labels: NOT YET PROCESSED
