### ISSUE TITLE
NoHassleAV 16x16 HDMI Matrix

### ISSUE THREAD

**Issue by jcborn93** [bitfocus/companion-module-requests#878] opened 2022-08-24 02:51 UTC
Can support be added for this 16x16 Mixer from NoHassleAV?https://www.nohassleav.com/support/matrix_hdmi_16x16_4k/

**Comment by josephdadams** [comment] 2022-08-27 20:14
probably a duplicate of #846

**Closed by josephdadams** 2022-08-27 20:14 UTC
Labels: Missing documentation, Hardware

**Comment by SkylerJEhly** [comment] 2022-10-15 13:01
Hi @jcborn93 I implemented this alongside [#846](https://github.com/bitfocus/companion-module-requests/issues/846). If you send me an email (found on my profile) I'll send you over an early alpha for you to test.
