### ISSUE TITLE
Behringer X-touch

### ISSUE THREAD

**Issue by Gerry-Clark** [bitfocus/companion-module-requests#1276] opened 2023-09-25 23:04 UTC
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Behringer X-touch

What you would like to be able to make it do from Companion:
Integrate with vMix to add tactile audio mixing.

Direct links or attachments to the ethernet control protocol or API:

**Comment by peternewman** [comment] 2023-09-26 11:41
Hi @Gerry-Clark ,

Unfortunately I don't know any details, but I know of some people using X-touch with vMix already, so it's presumably already possible with Companion or more likely they're doing it without companion and talking directly to vMix. Sorry for the lack of detail, but I figured the fact its possible might be useful info regardless.

**Comment by Julusian** [comment] 2023-09-27 10:11
I think this is a duplicate of https://github.com/bitfocus/companion/issues/1709

**Closed as completed by Julusian** 2023-09-27 10:11 UTC
Labels: NOT YET PROCESSED
