### ISSUE TITLE
Request for control to ADJ MY DMX 3.0 software light triggers on live mode

### ISSUE THREAD

**Issue by djenice** [bitfocus/companion-module-requests#1151] opened 2023-05-10 05:19 UTC
My Dmx 3.0 is a software operated under American dj. which allows production operators to control dmx lighting. It will be awesome to be able to toggle live presets through my dmx on a live show while using abs toggle buttons as well. 

<img width="234" alt="Screen Shot 2023-05-10 at 1 16 25 AM" src="https://github.com/bitfocus/companion-module-requests/assets/133072559/119ac900-c319-4f23-a8ed-e3a7343b2d9e">

**Comment by peternewman** [comment] 2023-05-20 14:41
Isn't this a duplicate of #1038 ?

**Closed as completed** 2023-06-28 12:56 UTC
Labels: NOT YET PROCESSED

**Comment by peternewman** [comment] 2023-06-28 20:17
Thanks @josephdadams .

FYI you can also officially mark it as a duplicate:
https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate

You should be able to mark it as closed in a not completed way too, which might be more appropriate...
