### ISSUE TITLE
Default OSC bindings for MA3

### ISSUE THREAD

**Issue by MMagneson** [bitfocus/companion-module-requests#980] opened 2022-11-29 11:54 UTC
Easy to use default set of commands for MA3 via OSC. Manually typing commands gets tedious fast, so this would be more of an easier/quicker way of setting up a MA3 OSC communication, much like for QLab.

With optional prefix set under Companion connections, an example input for playbacks could look like this:
Page [X], Fader [Y], Value [Z]

OSC output would look like this:
(/prefix)/PageX/FaderY,i,Z

For common commands, for instance GO, GO-, skip forward and so on, the easiest mode now is to send a command, where the OSC output would look like this for each respectively:
(/prefix)/cmd,s,"go"
(/prefix)/cmd,s,"go-"
(/prefix)/cmd,s,">>>"

I can assist in getting this going command/syntax-wise if someone can deal with the module specific things in Companion (I also speak norwegian if that helps)

**Comment by josephdadams** [comment] 2022-12-02 17:07
seems like a duplicate of bitfocus/companion-module-malighting-grandma3#1

**Closed as completed by josephdadams** 2022-12-02 17:07 UTC
