### ISSUE TITLE
AV MATRIX HVS0402U switcher video command

### ISSUE THREAD

**Issue by maoskip** [bitfocus/companion-module-requests#1316] opened 2023-11-16 16:43 UTC
Dear Sir, can you implemet the connection for the AV MATRIX HVS0402U switcher video?
Now I use a UDP command but it is not easy and complet, also without command feedbac...
Many thanks in advance!
Maurizio

**Comment by peternewman** [comment] 2023-11-19 01:24
I think this is a duplicate of https://github.com/bitfocus/companion-module-requests/issues/1285

**Comment by bryce-seifert** [comment] 2023-11-21 00:36
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1285

**Closed as not planned by bryce-seifert** 2023-11-21 00:36 UTC
