### ISSUE TITLE
Support for Atomos Shogun Studio control via AMP (Advanced Media Protocol)

### ISSUE THREAD

**Issue by bryancj** [bitfocus/companion-module-requests#940] opened 2022-10-18 13:46 UTC
Atomos Shogun Studio supports triggering the recording over the network through AMP but I don't see a module for it. I'm unsure if there is another way to send these commands through Companion. I have included a screenshot of the commands from the manual.
![Screen Shot 2022-10-18 at 8 46 30 AM](https://user-images.githubusercontent.com/51339777/196447758-68be2ea9-80b4-43fd-97de-9b13cbe5dc70.png)

**Comment by josephdadams** [comment] 2022-11-24 15:01
duplicate of #178

**Closed by josephdadams** 2022-11-24 15:01 UTC
