### ISSUE TITLE
Clear Com for Stream Deck

### ISSUE THREAD

**Issue by GmanMorelos** [bitfocus/companion-module-requests#1357] opened 2023-12-30 23:57 UTC
I want to know if anyone can make something to have a Stream Deck control Clear-Com, Thank you.

**Comment by bryce-seifert** [comment] 2023-12-31 13:56
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/364 or possibly https://github.com/bitfocus/companion-module-clearcom-station-ic/issues/1

**Closed as not planned by bryce-seifert** 2023-12-31 13:56 UTC

**Comment by SM0VXI** [comment] 2024-07-28 07:23
Clearcom have several different products, and there may be different API:s for different products.
 The API protocol to control their Eclipse HX matrix is called HCI (Host Control Interface). In order to control a matrix with HCI protocol a licence must be purchased (for each matrix). More information can be found here:

https://www.clearcom.com/Product/hci-host-control-interface?id=20929
