### ISSUE TITLE
Sharp PN-LE901

### ISSUE THREAD

**Issue by JeffNeubauer** [bitfocus/companion-module-requests#95] opened 2019-09-22 01:02 UTC
https://siica.sharpusa.com/Portals/0/downloads/Manuals/PN-LE%20_Quick_Start_Setup_Guide.pdf

**Comment by josephdadams** [comment] 2019-09-22 02:03
Duplicate of #96 and not enough info anyway.

**Closed by josephdadams** 2019-09-22 02:03 UTC
