### ISSUE TITLE
MIDI protocol integration (USB)

### ISSUE THREAD

**Issue by wesleyfernandess** [bitfocus/companion-module-requests#1248] opened 2023-08-23 14:00 UTC
I did the tests in the experimental version with support for Contour devices (Express and ShuttlePRO) I found it sensational and I did tests with Jog and Shuttle working perfectly.

I would like to request integration with devices that use the MIDI protocol via USB, there are several controllers on the market that can be used inside the companion in an intuitive way and above all at a low cost.

I have 4 MIDI controllers for testing here

**Comment by peternewman** [comment] 2023-08-24 01:34
> I did the tests in the experimental version with support for Contour devices (Express and ShuttlePRO) I found it sensational and I did tests with Jog and Shuttle working perfectly.

Off topic but that's great news if you've used the Express since https://github.com/bitfocus/companion/issues/2430 . Did the button mapping work in a logical way?

Fancy doing a PR to remove this line:
https://github.com/bitfocus/companion/blob/0f91aeffe2f974c72b406d11587e0f92d26c2eca/lib/Surface/USB/ContourShuttle.js#L30

Also was it a Pro or Pro v2, and if the former likewise for the equivalent line for that device?

**Comment by phillipkliewer** [comment] 2023-09-09 20:27
Doesn't midi-relay already do this?

**Comment by Julusian** [comment] 2023-09-20 22:00
Duplicate of https://github.com/bitfocus/companion/issues/1709

**Closed as not planned by Julusian** 2023-09-20 22:00 UTC
Labels: NOT YET PROCESSED
