### ISSUE TITLE
Bitfocus Companion Module for Zowiebox

### ISSUE THREAD

**Issue by amwtech1** [bitfocus/companion-module-requests#1545] opened 2024-07-08 22:27 UTC
I would like a bitfocus companion module to control a Zowiebox. https://www.zowietek.com/product/4k-video-streaming-encoder-decoder/ This is an excellent little NDI, Streaming, and Tally device all rolled into one. Having Companion button control to control tally color even when an NDI device is not connected would be great. It would also be nice for the tally color to change based on the preview and program of an ATEM. Other functions might include starting and stopping the streaming functions. Here is the link to their API inquiry: https://www.zowietek.com/api/

Thank you!!!

**Comment by JeLuF** [comment] 2024-07-17 18:16
Duplicate of #1438?

**Closed as not planned** 2024-07-21 15:24 UTC
