### ISSUE TITLE
Loxone Integration

### ISSUE THREAD

**Issue by 07pepa** [bitfocus/companion-module-requests#1374] opened 2024-01-18 15:00 UTC
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Loxone

What you would like to be able to make it do from Companion:
read states of block (on/off)  
read all values (as variables)
change state (nothing complicated just on off or switch to certain percentage ... i do not want to control spot price optimizer, temperature plans ranges etc...)

Direct links or attachments to the ethernet control protocol or API:
https://www.loxone.com/enen/kb/api/
https://github.com/Loxone/lxcommunicator

**Comment by bryce-seifert** [comment] 2024-01-20 22:24
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/730

**Closed as not planned by bryce-seifert** 2024-01-20 22:24 UTC
Labels: Software
