### ISSUE TITLE
OBSBOT - TAIL CAMERA

### ISSUE THREAD

**Issue by Tonio006** [bitfocus/companion-module-requests#1549] opened 2024-07-11 15:40 UTC
Hello, 

thx for the very nice companion app, is it possible for you to add the OBSBOT - TAIL CAMERA remote in companion ?

Thxs 

Regards

**Comment by bryce-seifert** [comment] 2024-07-21 15:22
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/567

**Closed as not planned by bryce-seifert** 2024-07-21 15:22 UTC
