### ISSUE TITLE
Sky HD Box

### ISSUE THREAD

**Issue by ojwilliams** [bitfocus/companion-module-requests#1450] opened 2024-03-31 14:24 UTC
I want to be able to control my Sky HD Boxes remotely. The following program allows command-line access to the Sky boxes. It looks like a TCP command.

https://github.com/dalhundal/sky-remote 
https://github.com/dalhundal/sky-remote-cli

action buttons could fire the following commands: Remote control commands
sky power

tvguide or home boxoffice services or search interactive or sidebar

up down left right select

channelup channeldown i

backup or dismiss text help

play pause rewind fastforward stop record

red green yellow blue

0 1 2 3 4 5 6 7 8 9

**Comment by dnmeid** [comment] 2024-03-31 15:07
duplicate of #1393

**Closed as not planned by dnmeid** 2024-03-31 15:07 UTC
