### ISSUE TITLE
Update Allen&Heath Qu module to 3.x

### ISSUE THREAD

**Issue by DPalmer-FCB** [bitfocus/companion-module-requests#1298] opened 2023-10-28 20:02 UTC
The feedbacks don't work with the Allen&Heath QU module (https://github.com/bitfocus/companion-module-allenheath-qu) in Companion 3.x.  I looked at updating the module myself but it is beyond my expertise.  Hoping someone can fix the feedbacks and bring it up to the 3.x level.  All of the Allen & Heath mixer connections (modules) seem to have the orange triangle.  For reference, I have attached a copy of the Qu MIDI Protocol document.

[Qu_MIDI_Protocol_V1.9.pdf](https://github.com/bitfocus/companion-module-requests/files/13196612/Qu_MIDI_Protocol_V1.9.pdf)

**Comment by bryce-seifert** [comment] 2023-10-30 21:55
Duplicate of https://github.com/bitfocus/companion-module-allenheath-qu/issues/18

**Closed** 2023-10-30 21:55 UTC

**Comment by DPalmer-FCB** [comment] 2023-10-31 05:11
This is not actually a duplicate.  The feedbacks are currently not working in the Qu Module.  I didn't realize this when I wrote on https://github.com/bitfocus/companion-module-allenheath-qu/issues/18.  I would like to at least see the feedbacks fixed.  It would also be a plus if the orange triangle with the exclamation point wasn't there.  Thx!
