### ISSUE TITLE
Allen & Heath CQ Series

### ISSUE THREAD

**Issue by AlexRobinsonTV** [bitfocus/companion-module-requests#1324] opened 2023-11-23 03:33 UTC
Just picked up a new Allen & Heath CQ-12t. I see a number of Allen & Heath consoles available already on Companion and these new CQ Series consoles support remote control over ethernet via their own app. 

- Input On/Off toggle
- Rec start/stop toggle

**Comment by peternewman** [comment] 2023-12-02 23:50
This is a more generic duplicate of the older https://github.com/bitfocus/companion-module-requests/issues/1280

**Closed as not planned** 2023-12-15 02:37 UTC

**Comment by taewon1234** [comment] 2024-04-13 07:12
This product is selling very well these days, so we would appreciate your support.^^ 
Allen & Heath CQ-12t.
Allen & Heath CQ-18t.
Allen & Heath CQ-20B

**Comment by tehsu** [comment] 2024-06-05 03:40
the midi support is available now

**Comment by pdelbracio** [comment] 2024-06-07 11:41
I couldn't find a module for CQ available. 
@tehsu 
Where can you find that midi support you mentioned

**Comment by taewon1234** [comment] 2024-06-07 12:26
Hello, I can't search for the model name in companion 3.3.1.
thank you

2024년 6월 7일 (금) 오후 8:41, pdelbracio ***@***.***>님이 작성:

**Comment by taewon1234** [comment] 2024-06-07 12:36
Bitfocus Companion v3.3.1📦 Downloads available at

   - https://user.bitfocus.io/download

💵 Donate to the project at

   - open collective https://opencollective.com/companion
   - or via https://donorbox.org/bitfocus-opensource

Companion v3.3.1 - Release Notes🐞 BUG FIXES

   - Less agressive log rotating #2895
   - Add error handler for logStream writer #2895
   - Handle 'node-machine-id' failures #2885
   - Ensure variables in presets button text get replaced correctly #2837
   - 'Abort all delayed actions on a page' not respecting 'use variables'
   checkbox #2877
   - Apply wizard style

🐞 MODULE FIXES

   - aimedia-lexilive
   - aten-matrix
   - avstumpfl-pixera
   - barco-eventmaster
   - behringer-xair
   - figure53-qlab-advance
   - generic-dataentry
   - generic-tcp-serial
   - middleman-breaktime
   - ptzoptics-visca
   - roku-tv
   - roland-v160hd
   - sony-serialtally
   - studiocoast-vmix
   - tascam-cd
   - tascam-cd400u
   - tascam-da-6400
   - telestream-prism
   - videolan-vlc
   - vitec-avediaplayer9300-series
   - zenvideo-ndirouter

*Full Changelog*:
https://github.com/bitfocus/companion/compare/v3.3.0...v3.3.1

2024년 6월 7일 (금) 오후 9:26, Taewon Kim ***@***.***>님이 작성:

**Comment by AlexRobinsonTV** [comment] 2024-06-17 17:51
Midi Protocol Data Sheet
https://www.allen-heath.com/content/uploads/2024/06/CQ_MIDI_Protocol_V1_2_0_iss1.pdf
