### ISSUE TITLE
Module request: Multicam Suite

### ISSUE THREAD

**Issue by berryv97** [bitfocus/companion-module-requests#163] opened 2020-02-19 11:38 UTC
Hi,
Support for Multicam Suite would be great!
Regards,
Vincent
For more information:
[API Multicam 1.0(2).pdf](https://github.com/bitfocus/companion-module-requests/files/4224825/API.Multicam.1.0.2.pdf)

**Comment by josephdadams** [comment] 2020-02-19 12:54
Duplicate of #17

**Closed by josephdadams** 2020-02-19 12:54 UTC
