### ISSUE TITLE
I would love to see a profile built for HuddleCamHD Simple Track Lite

### ISSUE THREAD

**Issue by Sydmatthes** [bitfocus/companion-module-requests#962] opened 2022-11-07 20:10 UTC
https://huddlecamhd.com/support-utilities/

I would like to be able to trigger individual camera P, T Z
I would like to be able to trigger individual camera tracking feature
I would like to be able to trigger individual camera presets

**Comment by josephdadams** [comment] 2022-11-08 17:22
this is a duplicate of #848

**Closed by josephdadams** 2022-11-08 17:22 UTC

**Comment by Sydmatthes** [comment] 2022-11-08 17:27
Apologize I added the requested material in this one.

Syd
