### ISSUE TITLE
Pixelhue P10

### ISSUE THREAD

**Issue by balazsantal** [bitfocus/companion-module-requests#1323] opened 2023-11-22 16:22 UTC
Hi there, 

Could you do the Pixelhue P10 contorl for companion:

- Pixelhue P10 / Pixelflow software
- Change presets

Thank you in advance!

Balazs

**Comment by bryce-seifert** [comment] 2023-12-15 02:41
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1292

**Closed as not planned by bryce-seifert** 2023-12-15 02:41 UTC
