### ISSUE TITLE
Companion support for AV-Matrix Switchers VS0601U and Shark S6

### ISSUE THREAD

**Issue by RatHimself** [bitfocus/companion-module-requests#1703] opened 2024-12-05 15:03 UTC
Companion support for AV-Matrix video switchers, especially VS0601U and Shark S6 models.
https://www.avmatrix.com/products/mini-6ch-steaming-video-switcher-vs0601u
Equivalent control set as to that offered for BMD ATEM switchers.
Thanks.

**Comment by dnmeid** [comment] 2024-12-05 15:47
Duplicate of #1285 #944

**Closed as not planned by dnmeid** 2024-12-05 15:47 UTC
