### ISSUE TITLE
Boxcast multisite player

### ISSUE THREAD

**Issue by davidmctech** [bitfocus/companion-module-requests#919] opened 2022-09-30 19:48 UTC
Would love if there was a way to control boxcast from another computer via stream deck

**Comment by ashep42** [comment] 2023-11-07 21:41
Hi, 

Does this have any updates?  I would like to be able to control Boxcast via Companion as well.

**Comment by daniep01** [comment] 2023-11-07 22:34
[https://boxcast.github.io/boxcast_api/](https://boxcast.github.io/boxcast_api/)

It might be possible to make a module, depending on what you wish to do.

**Comment by ashep42** [comment] 2023-11-07 22:55
I’d like to be able to stop a broadcast stream. We have our live streams start at a set time for each meeting but the ending time is never the same.

Sent from my iPhone




Allison Shepherd
AV Engineer
Information Technology
York County Government

________________________________

***@***.***
Phone: 803-684-8570


       [cid:logo_ccdf8981-cba4-4eb5-9abc-30b7830ad94d.png] <http://www.yorkcountygov.com/>    [cid:Facebook_39bbb7bd-ea9f-458b-ba84-03ff3f2ce399.png] <https://www.facebook.com/YorkCountySc/>   [cid:Twitter_6aba590a-5e26-4ec6-88b4-5a6171d3a81a.png] <https://twitter.com/yorkcountyscgov>

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary, and/or privileged information protected by law. If you are not the intended recipient, you may not read, use, copy, or distribute this e-mail message or its attachments. If you believe you have received this e-mail message in error, please contact the sender by reply e-mail or telephone immediately and destroy all copies of the original message. "Any information provided on this email, including any attachments, may be subject to the South Carolina Freedom of Information Act and may be disclosed to third parties in accordance with applicable law."

On Nov 7, 2023, at 5:34 PM, Peter ***@***.***> wrote:

﻿
WARNING: The email below is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
________________________________


https://boxcast.github.io/boxcast_api/<https://boxcast.github.io/boxcast_api/>

It might be possible to make a module, depending on what you wish to do.

**Comment by josephdadams** [comment] 2024-08-29 17:50
duplicate of #35

**Closed by josephdadams** 2024-08-29 17:50 UTC
Labels: Missing documentation

**Comment by josephdadams** [comment] 2024-09-17 21:06
This module is now in the betas.
