### ISSUE TITLE
Allen and Heath SQ

### ISSUE THREAD

**Issue by simongroom112** [bitfocus/companion-module-requests#271] opened 2020-08-27 12:46 UTC
Request for support on Allen and Heath SQ console range.

Link to MIDI documentation below. 
https://www.allen-heath.com/media/SQ-MIDI-Protocol-Issue2.pdf

Have a want/need for support for this from September 2020

Can support with testing fairly instantly as own one of these consoles already.

**Comment by josephdadams** [comment] 2020-08-27 17:40
Duplicate of #56

**Closed by josephdadams** 2020-08-27 17:40 UTC
