### ISSUE TITLE
Novastar J6

### ISSUE THREAD

**Issue by Rahulhasmail** [bitfocus/companion-module-requests#675] opened 2021-12-28 11:58 UTC
Please create Control Module for J6

only preset change is also fine

https://www.novastar.tech/products/processors/
J6
https://www.novastar.tech/downloads/
V-Can
Thank You

**Comment by Rahulhasmail** [comment] 2022-01-12 08:09
https://www.novastar.tech/products/vp/j6/

Hi @josephdadams
Greetings!

We need this module.
its a request, how can this be done, 
in documentation what you need please guide.

Or we can talk over call for better understanding.

Thanks & Regards,
Rahul Chawda
9970955256

**Comment by josephdadams** [comment] 2022-01-12 14:05
I would suggest reaching out to @rit3sh7 as he seems to have strong knowledge of these processors and their protocols. Perhaps you can hire him to create this for you.

I will close this as it is a duplicate of bitfocus/companion-module-novastar-controller#36

**Closed by josephdadams** 2022-01-12 14:05 UTC
Labels: Missing documentation, Hardware

**Comment by Rahulhasmail** [comment] 2022-01-13 07:46
Will Update You EOD Today<

Thanks a lot...!

**Comment by Rahulhasmail** [comment] 2022-01-13 11:16
@rit3sh7  Checked using Given Companion Version: (2.2.0-7fd8169a-3716)

J6 Freezez as soon as we load preset: 
Current J6 firmware Vesion: V3.0.0.0

V-Can Version : 3.6
J6  is used in Slicer Mode:

if any info requred plz feel free to ask

Thanks
