### ISSUE TITLE
Roland VR-6 HD compability request/questions

### ISSUE THREAD

**Issue by pawelco** [bitfocus/companion-module-requests#1542] opened 2024-07-05 13:24 UTC
Hello
I"d like to control my PTZ cameras on Roland VR-6 HD using streamdeck  or MDI controller via Companion.
I see that the VR-120 HD preset is already there. I assume that it's just a case of adding sys-ex controls to make the VR-6 work.
If not- what's the way of programming the library?
Or maybe someone already has a proper file to share.
Thanks

**Comment by JeLuF** [comment] 2024-07-08 15:30
The parameter address map of the VR-6 HD, as documented in https://static.roland.com/assets/media/pdf/VR-6HD_Control_eng02_W.pdf, is different from the VR-120 HD, so yes, new sys-ex controls are needed.

The modules are written in either Javascript or Typescript. The VR-120 HD module (written in Javascript) is available at https://github.com/bitfocus/companion-module-roland-vr120hd

There's a [Module Development 101](https://github.com/bitfocus/companion-module-base/wiki/Module-development-101) in the wiki. It explains how to set up a dev environment and how to submit the module for inclusion to Companion.

**Comment by bryce-seifert** [comment] 2024-07-21 15:19
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1443

**Closed as not planned by bryce-seifert** 2024-07-21 15:19 UTC
