### ISSUE TITLE
Stream Deck Integration for Worship Tools Presenter

### ISSUE THREAD

**Issue by khainghtoo18** [bitfocus/companion-module-requests#1618] opened 2024-09-18 23:50 UTC
Hi, I would like to request the integration of Worship Tools Presenter with the Elgato Stream Deck.
Stream Deck integration would allow users to quickly and efficiently control Worship Tools Presenter during live worship services. It could help streamline operations by providing easy access to key functions like:
Advancing or going back to slides
Launching or stopping presentations
Triggering pre-configured media or lighting cues
Muting/unmuting audio
Changing scenes for live streaming setups
This feature would greatly benefit those using Presenter in a live production environment where timing and quick transitions are crucial.
Thanks for considering this feature request!

**Comment by josephdadams** [comment] 2024-10-04 18:32
duplicate of #1385

**Closed as completed by josephdadams** 2024-10-04 18:32 UTC
