### ISSUE TITLE
Panasonic AW-RP60

### ISSUE THREAD

**Issue by cisti3000** [bitfocus/companion-module-requests#377] opened 2021-01-28 12:37 UTC
I already used companion with other camera controller from Panasonic, on this work now I have to use it with the new RP60. I hoped that for basic commands it would have worked the module for the RP50 with just a little less customization, but unluckily it didn't work. Thanks to all the community for all you already realized!

**Comment by McHauge** [comment] 2021-01-28 12:42
Hi, I'm closing this since it's a duplicate of a duplicate. Take a look at the issues on the Panasonic-camera-control module, I think this is the third request for this unit in 7-10 days, this would be an addition to an existing module, not a new module. In the at module, you will also see the discussion of adding support for all Panasonic PTZ controllers.

**Closed by McHauge** 2021-01-28 12:42 UTC
