### ISSUE TITLE
Module to control Bitfocus Companion

### ISSUE THREAD

**Issue by jpooley-hearst** [bitfocus/companion-module-requests#414] opened 2021-03-01 22:32 UTC
Hi, 

Requesting a module to control another instance of Bitfocus Companion. This is currently possible via the generic HTTP module. This will allow multiple physical Stream Deck "clients" to be able to trigger the same action on the central Companion "server". 

Thanks for your consideration

**Comment by JeffreyDavidsz** [comment] 2021-03-01 22:36
I think what you need is the Companion-satelite app, search for it @ facebook. With that you can use a streamdeck on an other pc/mac but connected via LAN to a Companion "server"

**Comment by jpooley-hearst** [comment] 2021-03-01 22:40
Hey Jeffrey, 

I've already got my configuration working with generic HTTP without requiring additional software. From an enterprise perspective that's preferable. Just putting in a request as suggested on the generic HTTP module interface.

**Comment by JeffreyDavidsz** [comment] 2021-03-02 21:44
So you would like to see some presets?

**Comment by jpooley-hearst** [comment] 2021-03-03 22:08
The ability to select a bank and button to trigger would be great

**Comment by josephdadams** [comment] 2021-03-07 21:20
Duplicate of #304

**Closed by josephdadams** 2021-03-07 21:20 UTC
