### ISSUE TITLE
Support for Avid Pro Tools DAW, with support for Antares Auto Tune

### ISSUE THREAD

**Issue by acknapp2012** [bitfocus/companion-module-requests#788] opened 2022-04-23 18:56 UTC
I'm looking for support in Companion for Avid Pro Tools digital audio workstation, with a specific need to also support the Antares Auto-Tune plugin. This is so I can easily change the key of a song in Auto-Tune with just a button press on the Streamdeck. I was unable to see that it is currently supported, although I did notice that Reaper DAW is supported.

**Comment by dmitrylive** [comment] 2022-08-16 23:50
I would also like to see AVID Pro Tools

**Comment by Teressss** [comment] 2022-11-19 13:52
I agree, support for Avid Pro Tools would be amazing!

**Comment by Xanderdanny** [comment] 2022-12-02 21:51
I agree, too. Support for Avid Pro Tools would make our work faster and easier!

**Comment by josephdadams** [comment] 2024-01-07 00:01
duplicate of #598

**Closed by josephdadams** 2024-01-07 00:01 UTC
Labels: Missing documentation, Software
