### ISSUE TITLE
Streamdeck - LiveStream Studio 6 web streaming software

### ISSUE THREAD

**Issue by chrismorrissey94** [bitfocus/companion-module-requests#191] opened 2020-03-30 18:24 UTC
Hi,
I would like to be able to use my stream deck to control LiveStream Studio 6

Ideally it would be able to offer the ability to choose different input sources on the Preview screen, with CUT and AUTO take buttons, and also offer the ability to change the Program feed inputs directly 

Thanks,

Chris

**Comment by josephdadams** [comment] 2020-03-30 21:50
Duplicate of #119. Feel free to use the search function for keywords to double check and see if someone else has already submitted a request.

**Closed by josephdadams** 2020-03-30 21:50 UTC
