### ISSUE TITLE
Resi Stop Broadcast

### ISSUE THREAD

**Issue by dustenharward** [bitfocus/companion-module-requests#501] opened 2021-05-10 22:18 UTC
**Describe the feature**
I would like the ability to end the Resi live broadcast, or drop a cue into the stream from the encoder that would let the system know where to stop the broadcast. 

**Usecases**
We are using the encoder to push to our web platforms and only have an encoder not a decoder. I see there is a living as one decoder option, but that does not work for the use of only the encoder to web. Right now I have to login to the web and stop the YouTube broadcast and the Facebook broadcasts separately.

**Comment by philipcain** [comment] 2021-05-31 18:10
There isn't a public API for controlling Resi Encoders; the hardware can only be controlled from the Resi Control Web panel (or in the case of the ProPresenter Encoder, from ProPresenter). You need to submit a [feature request directly to Resi](https://resi.io/contact/) to allow for external/remote encoder control, or ask them to build an Encoder module for Companion.

**Comment by josephdadams** [comment] 2024-11-12 22:27
duplicate of #880

**Closed by josephdadams** 2024-11-12 22:27 UTC
Labels: Missing documentation, Hardware
