### ISSUE TITLE
AVMATRIX PVS0403u

### ISSUE THREAD

**Issue by oleamundsen** [bitfocus/companion-module-requests#1572] opened 2024-08-05 14:53 UTC
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:

What you would like to be able to make it do from Companion:

Direct links or attachments to the ethernet control protocol or API:

**Comment by oleamundsen** [comment] 2024-08-05 14:54
AVMATRIX PVS0403u

**Comment by dnmeid** [comment] 2024-08-05 22:45
duplicate of #1478 #936 #1401 #1456

**Closed as not planned by dnmeid** 2024-08-05 22:45 UTC
Labels: NOT YET PROCESSED
