### ISSUE TITLE
Fixed / Safe buttons

### ISSUE THREAD

**Issue by andreamatteobassi** [bitfocus/companion-module-requests#328] opened 2020-12-15 15:50 UTC
Good morning all! 

I think one nice features could be to have some fixed buttons on the surfaces. For example audio ON / audio OFF that is a button that is in the same position in all the 99 pages.

Thank you

**Comment by josephdadams** [comment] 2020-12-15 22:07
duplicate of https://github.com/bitfocus/companion/issues/27

**Closed by josephdadams** 2020-12-15 22:07 UTC
