### ISSUE TITLE
Request Visca Module for OBSBOT Tail Air

### ISSUE THREAD

**Issue by DroneDude1983** [bitfocus/companion-module-requests#1368] opened 2024-01-15 04:30 UTC
Can someone please make a midule more specific to the OBSBOT Tail Air.   Some of the commands from Sony Visca Module work and others dont work or dont work correctly.  

The White Balance does not work corectly and some of the commands are not in the list.

**Comment by bryce-seifert** [comment] 2024-01-20 22:20
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/567

**Closed as not planned by bryce-seifert** 2024-01-20 22:20 UTC
