### ISSUE TITLE
rodecaster pro

### ISSUE THREAD

**Issue by ruslankar** [bitfocus/companion-module-requests#1204] opened 2023-07-04 00:09 UTC
I'm a huge fan of bit focus companion. can you guys please work in rode caster pro ii integration so I can control it on my stream deck.

**Comment by bryce-seifert** [comment] 2023-07-04 19:24
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/885

**Closed as completed** 2023-07-05 13:20 UTC
