### ISSUE TITLE
Hisense TV Control 

### ISSUE THREAD

**Issue by gwadem** [bitfocus/companion-module-requests#1400] opened 2024-02-07 14:50 UTC
Control for Hisense TV's over LAN.  
Seems like it could be done through an MQTT connection: https://github.com/Krazy998/mqtt-hisensetv/blob/master/README.md

**Comment by bryce-seifert** [comment] 2024-02-09 23:27
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/837

**Closed as not planned by bryce-seifert** 2024-02-09 23:27 UTC
