### ISSUE TITLE
Add ability to communicate with HiQnet mixers (mute / unmute microphones).  The manufacturer is Soundcraft by Harmon.  

### ISSUE THREAD

**Issue by richardnewport54** [bitfocus/companion-module-requests#348] opened 2021-01-10 21:39 UTC
Companion has an interface for Soundcraft UI devices.  That uses a http protocol (port 80).  
HiQnet is a different protocol.  

I am willing to work on this solution.  
I need information on your standards for coding and example code snippets.  
I have read the HiQNet protocol and have the ability to test the code that is completed.  
I have wireshark experience. 
I have a ethernet switch with management so i can mirror the traffic to my computer to validatre testing.  
I have access to a Soundcraft Impact SI for testing.  
I have an Ipad with Visiremote software on it.
This way i can validate what the VisiRemote software sends to the Soundcraft board.    
The Ipad can do what i want.  

I have the Soundcraft HiQnet protocal standards manual.  

The primary feature needed is to mute and unmute microphones.  
A nice to have would be the ability to adjust fader levels not important at this time.  

I currently have an Elgato Stream Deck.  
I have 8 buttons that are used for the streaming features.
This is what i do with each of the buttons at this time.  
 
1. Turn off highlight of current (streamdeck button) for the camera
2. OBS - place a still image into the stream (for camera move). 
3. Reposition the PTZ camera to the next location to stream
4. Atem Mini select camera 2 (PTZ camera)
5. Atem Mini turn on Chroma Key 
6. OBS - place the camera 2 image to the screen (PTZ camera). 
7. Highlight the current camera button that was pressed. 

Would like to add functions for Soundcraft SI Impact mixer.
  1a. to mute the currently active microphones. 
   
   6a.  unmute appropriate microphones. 

Let me know what my next steps should be to start working on this?

Thank you
Rich Newport
rich.newport@wowway.com

**Comment by josephdadams** [comment] 2021-01-11 11:55
Duplicate of #174

**Closed by josephdadams** 2021-01-11 11:55 UTC

**Comment by a1fred0** [comment] 2021-05-27 19:08
Also see this repo as a possible starting point for nodejs module?
https://github.com/fabiankaestner/hiqnode
