### ISSUE TITLE
ATDM-0604a - Digital SmartMixer - Audio-Technica 

### ISSUE THREAD

**Issue by Chuskou** [bitfocus/companion-module-requests#973] opened 2022-11-22 11:04 UTC
Hi everyone!!

Ive been trying to connect my audotechnica  ATDM digital mixer with bitfocus companion and i havent found any module.

Is there anyway to get the module?

Thanks in advandce

**Comment by Chuskou** [comment] 2022-11-22 12:00
the module its an audiotechnica digital mixer ATDM-0604a - Digital SmartMixer

**Comment by josephdadams** [comment] 2022-11-24 14:37
All modules have to be coded by someone. It would be great if you could provide more information with your request, like what you are wanting to be able to do with the device through Companion, as well as links to the external control protocols that will enable Companion to control it.

**Comment by josephdadams** [comment] 2022-11-24 14:40
actually a duplicate of bitfocus/companion-module-audiotechnica-digitalmixer#2

**Closed by josephdadams** 2022-11-24 14:40 UTC
Labels: Missing documentation, Hardware

**Comment by Chuskou** [comment] 2022-11-28 09:38
Hi Joseph!! 
 First of all thank you in advandce for your quick replay back.

Id like to have control of input/output volume levels, sends, on/off channels, routing,.. etc.

I hope this could help out with the protocols that the mixer demands.

https://docs.audio-technica.com/all/IP_Control_Protocol_Specification_-_ATDM-1012_ATDM-1012DAN.pdf

**Comment by ehfyn** [comment] 2023-02-17 19:49
It would be so cool if a module was build for this! I have both the 0604 and 1012DAN mixers and run them together with AT-LINK.
Ive been able to trigger some functions with the TCP command strings, but can’t get any feedback. 
would love to see a module to handle these devices.

**Comment by josephdadams** [comment] 2023-02-17 20:12
It’s in progress and will be in companion v3 betas.

**Comment by ehfyn** [comment] 2023-02-27 20:59
That’s amazing news Joseph! Actually found your repository and read through some of the code (with my limited knowledge) and saw both the 0604, 0604a and the 1012 mentioned! That’s amazing news for me, since i run both.
I will look forward to testing the module and supply you with feedback! Let me know what you need in terms of tests etc. - i’m all in on a collaboration in that regard!

I’ll be playing with the AT Link tomorrow, and see how that actually works with linking a 1012 together with a 0604, just to get an idea of how that scenario would play with the IP control and the module you are working on.

But again - be sure to reach out to me, if you need anything tested :)
