### ISSUE TITLE
Sony Projector Integration for VPL-FHZ60's

### ISSUE THREAD

**Issue by roshjothe** [bitfocus/companion-module-requests#860] opened 2022-07-26 18:58 UTC
I work at a church, and we use two Sony VPL-FHZ60's. We currently can turn the projectors on and off using a network link. I have a friend attempting to build a web-scraper that can integrate with hotkeys on a streamdeck, but if there's an easier way to integrate with companion, that would be preferable. If you need any information about the projector I'm here to help! Thanks

**Comment by istnv** [comment] 2022-07-26 19:17
This projector supports the PJLink protocol.
Look for the PJLink module in Companion.

**Comment by josephdadams** [comment] 2022-08-05 17:03
duplicate of #372

**Closed by josephdadams** 2022-08-05 17:03 UTC
