### ISSUE TITLE
Decimator Multiviewers support, including DMON models, MD-QUAD and DECIMATOR_QUAD

### ISSUE THREAD

**Issue by QuentinBrown** [bitfocus/companion-module-requests#123] opened 2019-11-22 18:29 UTC
Whilst basic control of these is available using the GPI interface on the units the GPI controls represent a very basic subset of all the controls on the device which can be accessed via an app over USB or the on-device menus. 

See product pages here: https://www.decimator.com/Products/MultiViewers/MultiView.html

Unfortunately, there is no SDK available for the USB control of the units and Decimator have yet to be convinced that there is a business case for investing in developing one. I would imagine the USB commands are universal between Mac & Windows.

It may be possible to use USB snooping tools to learn the commands being issued by the app. This is beyond my technical expertise, but I am happy to follow a procedure to snoop on my DMON-6S if someone can lay that procedure out for me and people are willing to work with the results to begin implementing the USB commands into a module.

The reason for wanting this functionality is to create macros to control a combination of routing and the number of windows in concert with changing settings on other connected devices. 

For example I often have to monitor multiple cameras from my workstation onset. I have a BMD Switcher, BMD Smartscope Duo, Multiple LUT boxes and a Decimator DMON 6S. On occasion we may switch to using only one camera, sometimes 2 or more on a shot to shot basis. Whilst lining up I might also want to pull up a single camera with a side by side of the source image and image with LUT applied then quickly switch back to a multi view of all cameras.  Currently this kind of complicated change to both routing, number of views and layout is very slow and time-consuming to do through the Decimator App. There are also no hot keys in the app to enable automation or control through StreamDeck.

**Comment by haakonnessjoen** [comment] 2019-11-22 19:05
Duplicate of #83 I think. Unless these devices does not use the same software or usb protocol.

**Comment by QuentinBrown** [comment] 2019-11-23 15:03
Ah! Yes it is. Thanks for the link. 
I did have a look around to see if it was on the radar already but obviously didn’t look deep enough. I’ll keep future posts on the topic to that thread.

**Comment by josephdadams** [comment] 2019-11-23 15:29
Closing because it’s a duplicate.

**Closed by josephdadams** 2019-11-23 15:29 UTC
