### ISSUE TITLE
Mackie DL Console compatibility request

### ISSUE THREAD

**Issue by DJaketech** [bitfocus/companion-module-requests#1480] opened 2024-05-08 01:23 UTC
This would include compatibility with the Mackie DL1608, 32R, 16s, and 32s. All can be controlled from master fader 5 and mixing station. Would love to see a somewhat full implementation of control for these mixers

**Comment by dnmeid** [comment] 2024-05-08 07:51
duplicate of #965

**Closed as not planned by dnmeid** 2024-05-08 07:51 UTC

**Comment by DJaketech** [comment] 2024-05-08 11:34
My apologies. Did not realize there was a duplicate
