### ISSUE TITLE
Newtek NDI Router request

### ISSUE THREAD

**Issue by Hce0314** [bitfocus/companion-module-requests#1371] opened 2024-01-17 19:58 UTC
I would love to see a NDI tools router Connection for companion. For example, at the push of a Stream Deck button I could switch which source I want to use and which Output I want that NDI source to go to.

**Comment by bryce-seifert** [comment] 2024-01-20 22:19
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/869

**Closed as not planned by bryce-seifert** 2024-01-20 22:19 UTC
Labels: Missing documentation, Software
