### ISSUE TITLE
QLC+

### ISSUE THREAD

**Issue by marcusleonas** [bitfocus/companion-module-requests#1268] opened 2023-09-20 19:33 UTC
QLC+ is a free and open-source lighting console for Linux, Windows and macOS.

Website: [www.qlcplus.org/](https://www.qlcplus.org/)
Web Interface docs: [docs.qlcplus.org/v4/advanced/web-interface)](https://docs.qlcplus.org/v4/advanced/web-interface)

**Comment by Julusian** [comment] 2023-09-20 21:58
Duplicate of #612

**Closed as not planned by Julusian** 2023-09-20 21:58 UTC
