### ISSUE TITLE
Aida PTZ camera Control

### ISSUE THREAD

**Issue by thyREV** [bitfocus/companion-module-requests#486] opened 2021-04-24 05:23 UTC
Could you make a companion module to control the Aida PTZ-NDI-X20 camera? 

Thanks a lot

**Comment by josephdadams** [comment] 2021-05-03 00:12
Please provide documentation

**Comment by thyREV** [comment] 2021-05-03 00:36
Here's the manual. Thanks

**Comment by thyREV** [comment] 2021-05-03 00:38
Here is the manual

https://aidaimaging.com/wp-content/uploads/2020/11/AIDA-IPNDI-PTZ-manual-V2.1.pdf

**Comment by josephdadams** [comment] 2021-05-03 03:49
It supports VISCA over IP. You should just use one of the existing VISCA modules in Companion. Start with the sony one.

**Comment by bakfiets2** [comment] 2021-06-11 08:19
Yes. But the tally lights don't work...

**Comment by astrocasters** [comment] 2021-12-03 01:52
Updated link to the manuals:  https://aidaimaging.com/download
[AIDA-IPNDI-PTZ-manual-V2.1(1).pdf](https://github.com/bitfocus/companion-module-requests/files/7646253/AIDA-IPNDI-PTZ-manual-V2.1.1.pdf)
/

**Comment by josephdadams** [comment] 2022-07-09 13:40
duplicate of #281

**Closed by josephdadams** 2022-07-09 13:40 UTC
Labels: Hardware
