### ISSUE TITLE
Shelly IoT Relay

### ISSUE THREAD

**Issue by wtyeung** [bitfocus/companion-module-requests#668] opened 2021-12-15 03:29 UTC
shelly-pro-4pm-wifi-smart-home-automation

REST Spec : 
https://shelly-api-docs.shelly.cloud/gen2/

**Comment by rgischig** [comment] 2022-04-03 19:52
duplicate of https://github.com/bitfocus/companion-module-requests/issues/767

**Closed** 2024-03-31 16:18 UTC
Labels: Hardware
