### ISSUE TITLE
RESI Encoder

### ISSUE THREAD

**Issue by bfcmediaguys** [bitfocus/companion-module-requests#1668] opened 2024-11-03 16:41 UTC
I'd love to be able to use Companion with my Resi Encoder, especially with the new Go Live button. And to be able to stop an event and an encoder without having to log in to control would be super helpful.

**Comment by Phil0** [comment] 2024-11-06 10:13
Seems like there are some other open issues for RESI Encoders already. #501 #880

**Comment by josephdadams** [comment] 2024-11-12 22:27
duplicate of #880

**Closed as completed by josephdadams** 2024-11-12 22:27 UTC
