### ISSUE TITLE
Unreal OSC

### ISSUE THREAD

**Issue by mmcvfineart1** [bitfocus/companion-module-requests#1633] opened 2024-10-03 12:07 UTC
Hi there

It would be ace if you could add a connector to Unreal Engine's Remote Touch OSC.

https://dev.epicgames.com/documentation/en-us/unreal-engine/getting-started-with-remote-control-presets-in-unreal-engine

Warm regards,

mmcvfineart1

**Comment by thedist** [comment] 2024-10-03 12:18
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1005

**Closed as completed by thedist** 2024-10-03 12:18 UTC
