### ISSUE TITLE
Rogue Amoeba Farrago

### ISSUE THREAD

**Issue by DBinNYC** [bitfocus/companion-module-requests#1300] opened 2023-10-30 17:20 UTC
Mac Only Soundboard App from Rogue Amoeba - Farrago recently got OSC support. This is ripe for development. Whos up for the challenge?

https://rogueamoeba.com/support/manuals/farrago/?page=osc

**Comment by daniep01** [comment] 2023-10-30 19:21
Duplicate of #227

**Closed as not planned** 2023-10-30 19:49 UTC
